title: Hlengiwe Sinelile Dlamini
description: PhD Student | Critical Minerals | Cybersecurity
theme: minima


# Navigation links across the top of your site
header_pages:
  - background.md
  - dissemination.md
  - media.md
  - ngo-initiative.md

  # --- FORCE DARK MODE S&T COLORS HERE ---
sass:
  style: :compressed
  sass_dir: _sass
